version: "3.7"

services:
  app:
    container_name: "app"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/app
    env_file:
      - .env


  mongodb:
    container_name: "mongodb"
    image: "mongo:3.6.2"
    ports:
      - 27017:27017